version: '3.8'

services:
  flag-detection-service:
    build:
      context: .
      dockerfile: dockerfile
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
    container_name: flag-detection-container
    environment:
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}
      DJANGO_SETTINGS_MODULE: config.settings
      MT5_ACCOUNT: ${MT5_ACCOUNT}
      MT5_PASSWORD: ${MT5_PASSWORD}
      MT5_SERVER: ${MT5_SERVER}
    ports:
      - "8000:8000"  # Single port for both HTTP and ASGI
    env_file:
      - .env
    volumes:
      - .:/workspace
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 config.asgi:application"